
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[246] =
    {   0,
        0,    0,    0,    0,    0,    0,   90,   88,   85,   86,
       74,   88,   62,   63,   48,   46,   66,   47,   65,   49,
       87,   61,   68,   64,   45,   67,   44,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   69,   70,   88,   81,   76,   77,
       78,   89,   89,   83,   82,   84,    0,    0,   72,   38,
       38,    0,    0,    0,    0,    0,    0,   61,    0,   71,
        0,   43,   41,   42,   58,   58,   58,    0,   58,   58,
       58,   58,   58,   22,   58,   58,   58,   58,   58,   18,
       55,   58,   58,    6,   53,   58,   58,   58,   58,   25,

       58,   58,   58,   58,   58,   58,   58,   75,   79,    0,
        0,   38,   38,    0,   60,    0,   39,    0,    0,   59,
        0,   60,    0,   59,    0,   39,   40,    0,   52,   58,
       58,   58,   58,   58,   58,   51,   58,   58,   17,   58,
       23,   58,   58,   50,   54,   58,   58,   58,    5,   58,
       58,   58,    8,   58,   58,   58,   80,    0,   37,   37,
       32,   31,   60,   60,    0,   36,   35,   59,   59,   30,
       29,   60,   60,   34,   33,   59,   59,   40,    0,   58,
       58,   58,   15,   58,   58,   20,   58,   58,   58,   58,
       58,   58,   27,   13,   58,   19,   56,    3,   58,   26,

       58,   37,    0,   31,    0,   35,    0,   29,    0,   33,
        0,    4,   16,   58,    2,   58,   57,   58,   58,   58,
       58,   58,   58,   21,   28,    0,   58,   24,   58,   58,
       58,   58,   58,    7,   73,   14,    9,   58,   12,   58,
        1,   10,   58,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    5,    5,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    5,    5,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   44,   33,   45,   33,
       46,   47,   48,   49,   50,    5,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   33,   33,   60,   61,   62,
       63,   64,   33,   65,   66,   67,   68,   69,   70,   33,
       71,   33,   72,    5,   73,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    1,    2,    2,    2,    3,    2,    2,    2,
        2,    2,    2,    4,    2,    5,    6,    6,    2,    2,
        2,    2,    2,    7,    8,    7,    7,    7,    8,    9,
        9,    9,    9,    9,    9,   10,    9,    9,   10,    9,
       10,    9,   10,    9,    9,    2,    2,    2,    2,   11,
        7,    8,    7,    7,    7,    8,    9,    9,    9,    9,
        9,   10,    9,    9,   10,    9,   10,    9,   10,    9,
        9,    2,    2
    } ;

static const flex_int16_t yy_base[261] =
    {   0,
        0,    0,   71,   72,   73,   77,  698,  699,  699,  699,
      699,  650,  699,  699,  699,  699,  699,  699,   68,  699,
       73,   74,  674,  699,   72,  699,  673,   73,   77,   93,
      102,  108,  112,  644,  128,  110,  116,  138,   50,   53,
      131,  152,  121,  161,  699,  699,    0,  699,  699,  699,
      699,  690,  699,  699,  699,  699,  685,  684,  699,   78,
      188,  191,   82,  211,  640,   93,  635,  216,  224,  699,
      618,  699,  699,  699,  594,  171,  197,  593,  188,  132,
      163,  203,  105,   67,  206,  204,  214,  210,  216,  592,
      209,  234,  227,  591,  545,  230,  255,  232,  235,  543,

      241,  248,  250,  237,  251,  263,  542,  699,  699,  582,
      303,  307,  310,  286,  315,  323,  699,  326,  572,  185,
      294,  320,  571,  331,  332,  699,  335,  549,  535,  306,
      534,  314,  320,  316,  267,  533,  322,  332,  529,  327,
      335,  342,  347,  527,  526,  360,  362,  351,  525,  358,
      348,  371,  523,  373,  369,  365,  699,  412,  699,  418,
      408,  421,  425,  429,  431,  555,    0,  345,  395,  434,
      436,  440,  444,  535,    0,  448,  449,  450,  519,  424,
      423,  427,  496,  430,  434,  495,  444,  452,  437,  456,
      455,  431,  492,  490,  450,  486,  481,  443,  462,  441,

      464,  491,  504,  506,  472,    0,  508,  510,  424,    0,
      381,  341,  321,  487,  313,  381,  254,  479,  484,  500,
      503,  508,  506,  247,  205,  228,  499,  162,  512,  504,
      513,  522,  530,  146,  699,  135,  126,  532,   91,  531,
       66,   63,  519,   47,  699,  596,  607,  617,  624,  629,
      637,  644,  649,  653,  660,  665,  669,  674,  678,  682
    } ;

static const flex_int16_t yy_def[261] =
    {   0,
      245,    1,  246,  246,  247,  247,  245,  245,  245,  245,
      245,  248,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  245,  245,  250,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  251,  245,  245,
      245,  245,  245,  245,  252,  245,  253,  245,  245,  245,
      245,  245,  245,  245,  249,  249,  249,  254,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  255,  256,
      245,  245,  257,  258,  245,  245,  245,  245,  249,  249,
      254,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  255,  259,  256,  256,  245,
      245,  245,  245,  257,  260,  258,  258,  245,  245,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  245,  245,  245,  255,  259,  245,  245,  257,  260,
      245,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  245,  249,  249,  249,  249,
      249,  249,  249,  249,  245,  249,  249,  249,  249,  249,
      249,  249,  249,  249,    0,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static const flex_int16_t yy_nxt[773] =
    {   0,
        8,    9,   10,    9,    8,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       34,   35,   34,   34,   36,   37,   38,   39,   40,   41,
       42,   34,   43,   44,   34,   45,    8,   46,    8,   47,
       28,   29,   30,   31,   32,   33,   34,   34,   35,   34,
       36,   37,   38,   39,   40,   41,   42,   34,   43,   44,
       34,   48,    8,   50,   50,   55,   51,   51,   53,   55,
       97,   59,   53,   60,   61,   61,   62,   62,   96,   68,
       68,   68,   71,   72,   73,  114,   78,   63,  115,   78,

       64,   69,   78,   65,   79,  111,  121,   97,   76,  122,
      137,   77,   78,   80,   96,   78,   78,   52,   52,   53,
       53,   53,   78,   81,   66,   53,   78,   64,   69,   82,
       67,   79,  111,   83,   76,   87,  137,   77,   84,   80,
       78,   85,   78,   86,  103,   56,   92,  136,   88,   56,
       81,   78,   93,   89,   78,   82,   90,   78,   98,   78,
       83,   78,   87,   91,   84,   78,   94,   85,  133,   86,
       78,  103,   92,  136,   88,   78,   95,   78,   93,   89,
       78,   78,   99,   90,   78,   98,  134,   78,  100,   91,
      101,  104,  105,   94,  133,   78,  102,  129,  119,  106,

      168,   78,   95,  112,  113,  113,   60,   61,   61,   99,
       78,   78,   78,  134,  100,  111,  101,  132,  104,  105,
       78,  116,  102,  116,  129,  106,  117,  118,  118,   62,
      139,   68,   68,   68,  125,  130,  125,   78,  135,  126,
      127,  127,  111,   69,  132,  138,   78,  140,  141,  143,
      235,  142,   78,   78,   78,   78,  118,  139,   78,   78,
      144,  130,  150,   78,  135,   78,  146,  145,  154,  118,
       69,  138,  149,  140,  141,  143,   78,  142,  147,   78,
      148,   78,  151,   78,   78,  152,   78,  144,  153,  150,
       78,  155,  146,  145,  156,  154,   78,   78,  149,   78,

       78,  161,  162,   78,   78,  147,  184,  148,  151,  170,
      171,  152,   78,  158,  153,  158,   78,  155,  159,  160,
      160,  156,  112,  112,  112,  112,  113,  113,  114,  180,
      163,  164,  184,  121,  111,  172,  173,  111,  117,  118,
      118,  165,  165,  165,  123,  181,  176,  126,  127,  127,
      178,  178,  178,  182,  183,   78,  180,  185,  119,  186,
      168,  111,   78,   78,  111,   78,  187,  189,  118,   78,
       78,   78,  181,  117,  190,  197,   78,  118,  188,  182,
      183,   78,  117,  185,   78,  191,  186,  195,  193,  192,
       78,   78,  187,  196,  189,  194,   78,   78,  198,  200,

       78,  190,  197,  226,  188,  201,  199,   78,  119,   78,
      168,   78,  191,  195,   78,  193,  192,  228,   78,  196,
       78,  194,   78,  203,  162,  198,  200,  159,  160,  160,
       78,  201,  199,  202,  202,  202,  204,  204,  114,  209,
      163,  164,  114,  228,  163,  164,  165,  165,  165,  207,
      171,  208,  208,  121,  214,  172,  173,  121,  213,  172,
      173,  123,  123,  176,  176,  178,  178,  178,  212,  222,
      215,  217,   78,   78,  216,  218,   78,  219,  117,   78,
       78,  214,  221,   78,  213,  220,   78,  205,  223,  224,
       78,  225,   78,   78,  212,  222,  215,  117,  217,   78,

      216,   78,  218,  219,   78,   78,  202,  202,  202,  221,
      227,   78,  220,   78,  223,  230,  224,  229,  225,  203,
      162,  204,  204,  207,  171,  208,  208,  231,   78,  232,
       78,  233,  234,   78,  236,   78,   78,  227,  237,   78,
      238,   78,  230,  229,   78,   78,  244,  211,   78,   78,
      209,  239,   78,   78,  231,   78,  232,   78,  233,  234,
      236,   78,   78,  240,  241,  237,  238,  242,   78,  243,
      205,   78,   78,  244,   78,   78,   78,  239,   78,   78,
       78,   78,   78,   78,   78,  179,  174,  166,  157,  240,
      241,   78,   78,  242,   78,  243,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   75,   75,
       75,   75,   75,   75,   75,  107,  107,  107,  107,  110,
       78,   78,   78,   78,  110,  128,  110,  120,  123,  120,
      120,  120,  124,  119,  124,  124,  124,  131,  131,  131,
      131,  131,  131,  131,  167,  167,  167,  167,  169,  169,
      169,  169,  169,  175,  175,  175,  175,  177,  177,  177,
      177,  177,  206,  206,  206,  206,  210,  210,  210,  210,
      109,  109,  108,   78,   74,   70,   58,  245,    7,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245
    } ;

static const flex_int16_t yy_chk[773] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    3,    4,    5,    6,
       40,   19,    6,   19,   19,   19,   21,   22,   39,   22,
       22,   22,   25,   25,   25,   63,  244,   21,   63,   39,

       21,   22,   40,   21,   29,   60,   66,   40,   28,   66,
       84,   28,  242,   29,   39,  241,   84,    3,    4,    3,
        4,    5,   28,   30,   21,    6,   29,   21,   22,   30,
       21,   29,   60,   31,   28,   33,   84,   28,   31,   29,
      239,   32,   30,   32,   43,    5,   36,   83,   33,    6,
       30,   31,   37,   33,   83,   30,   35,   32,   41,   36,
       31,   33,   33,   35,   31,   37,   38,   32,   80,   32,
       43,   43,   36,   83,   33,  237,   38,   35,   37,   33,
       41,   80,   42,   35,  236,   41,   81,   38,   42,   35,
       42,   44,   44,   38,   80,  234,   42,   76,  120,   44,

      120,   42,   38,   61,   61,   61,   62,   62,   62,   42,
       44,  228,   81,   81,   42,   61,   42,   79,   44,   44,
       76,   64,   42,   64,   76,   44,   64,   64,   64,   68,
       86,   68,   68,   68,   69,   77,   69,   79,   82,   69,
       69,   69,   61,   68,   79,   85,   77,   87,   88,   91,
      226,   89,   82,   86,  225,   85,   64,   86,   91,   88,
       92,   77,   99,   87,   82,   89,   96,   93,  104,   69,
       68,   85,   98,   87,   88,   91,   93,   89,   97,   96,
       97,   98,  101,   92,   99,  102,  104,   92,  103,   99,
      101,  105,   96,   93,  106,  104,  224,  102,   98,  103,

      105,  114,  114,  217,   97,   97,  135,   97,  101,  121,
      121,  102,  106,  111,  103,  111,  135,  105,  111,  111,
      111,  106,  112,  112,  112,  113,  113,  113,  115,  130,
      115,  115,  135,  122,  112,  122,  122,  113,  116,  116,
      116,  118,  118,  118,  124,  132,  124,  125,  125,  125,
      127,  127,  127,  133,  134,  130,  130,  137,  168,  138,
      168,  112,  215,  132,  113,  134,  140,  142,  116,  133,
      213,  137,  132,  118,  143,  151,  140,  125,  141,  133,
      134,  138,  127,  137,  141,  146,  138,  148,  147,  146,
      212,  142,  140,  150,  142,  147,  143,  151,  152,  155,

      148,  143,  151,  211,  141,  156,  154,  150,  169,  146,
      169,  147,  146,  148,  156,  147,  146,  216,  155,  150,
      152,  147,  154,  161,  161,  152,  155,  158,  158,  158,
      216,  156,  154,  160,  160,  160,  162,  162,  163,  209,
      163,  163,  164,  216,  164,  164,  165,  165,  165,  170,
      170,  171,  171,  172,  182,  172,  172,  173,  181,  173,
      173,  176,  177,  176,  177,  178,  178,  178,  180,  192,
      184,  187,  181,  180,  185,  188,  182,  189,  165,  184,
      192,  182,  191,  185,  181,  190,  189,  205,  195,  199,
      200,  201,  198,  187,  180,  192,  184,  178,  187,  195,

      185,  188,  188,  189,  191,  190,  202,  202,  202,  191,
      214,  199,  190,  201,  195,  219,  199,  218,  201,  203,
      203,  204,  204,  207,  207,  208,  208,  220,  218,  221,
      197,  222,  223,  219,  227,  196,  214,  214,  229,  194,
      230,  193,  219,  218,  186,  183,  243,  179,  227,  220,
      174,  231,  221,  230,  220,  223,  221,  222,  222,  223,
      227,  229,  231,  232,  233,  229,  230,  238,  243,  240,
      166,  232,  153,  243,  149,  145,  144,  231,  139,  233,
      240,  238,  136,  131,  129,  128,  123,  119,  110,  232,
      233,  107,  100,  238,   95,  240,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  249,  249,
      249,  249,  249,  249,  249,  250,  250,  250,  250,  251,
       94,   90,   78,   75,  251,   71,  251,  252,   67,  252,
      252,  252,  253,   65,  253,  253,  253,  254,  254,  254,
      254,  254,  254,  254,  255,  255,  255,  255,  256,  256,
      256,  256,  256,  257,  257,  257,  257,  258,  258,  258,
      258,  258,  259,  259,  259,  259,  260,  260,  260,  260,
       58,   57,   52,   34,   27,   23,   12,    7,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexical_analyzer.l"
#line 2 "lexical_analyzer.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <math.h>
    FILE *fp;

    // Part 1: Define the unique identifiers for each unit in the lexical analyzer

    #define T_eof 0
    #define T_id 1
    #define T_iconst 2
    #define T_rconst 3
    #define T_bconst 4
    #define T_cconst 5
    // Define the relational operators
    #define T_relop 6
    
    // Define the add operators
    
    #define T_addop 7
    
    // Define the logical OR operator
    #define T_or 13

    // Define the logical NOT operator
    #define T_not 15

    // Define the MULDIVAND operators
    #define T_muldivandop 16

    #define T_in 20     // IN

    // Define other lexical units
    #define T_lparen 21 // (
    #define T_rparen 22 // (
    #define T_semi 23   // ;
    #define T_dot 24    // .
    #define T_comma 25  // ,
    #define T_equ 26    // =
    #define T_colon 27  // :
    #define T_lbrack 28 // [
    #define T_rbrack 29 // ]
    #define T_assign 30 // :=
    #define T_dotdot 31 // ..

    // Define the keywords  // Keyword
    #define T_program 32    // PROGRAM
    #define T_const 33      // CONST
    #define T_type 34       // TYPE
    #define T_array 35      // ARRAY
    #define T_set 36        // SET
    #define T_of 37         // OF
    #define T_record 38     // RECORD
    #define T_var 39        // VAR
    #define T_forward 40    // FORWARD
    #define T_function 41   // FUNCTION
    #define T_procedure 42  // PROCEDURE
    #define T_integer 43    // INTEGER
    #define T_real 44       // REAL
    #define T_boolean 45    // BOOLEAN
    #define T_char 46       // CHAR
    #define T_begin 47      // BEGIN
    #define T_end 48        // END
    #define T_if 49         // IF
    #define T_then 50       // THEN
    #define T_else 51       // ELSE
    #define T_while 52      // WHILE
    #define T_do 53         // DO
    #define T_for 54        // FOR
    #define T_downto 55     // DOWNTO
    #define T_to 56         // TO
    #define T_with 57       // WITH
    #define T_read 58       // READ
    #define T_write 59      // WRITE

    // Define strings
    #define T_string 60
    // No need to define comments because they are ignored

    union  {
        unsigned int integer;
        double real;
        char str[1024];
        char character;
        int boolean;
    } yylval;
    char filename[256];
    int lines = 1;
    int errors = 0;
    double binary_to_decimal(const char* binary_string);
    double hex_to_decimal(const char* hex_string);
    void print_error(char *reason);
    
#line 792 "lex.yy.c"

#line 794 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 101 "lexical_analyzer.l"



#line 105 "lexical_analyzer.l"
// Part 2: Define the Regular Expressions for each of the identifiers and keywords
// Because PASC500 is case insensitive, we have to use '?i:' to denote it. 

// We start with the keywords because they can be perceived by the identifiers if we didn't
// search for them at first


#line 1025 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 699 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 112 "lexical_analyzer.l"
{printf("Keyword: program\n");  return T_program;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "lexical_analyzer.l"
{printf("Keyword: const\n");    return T_const;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "lexical_analyzer.l"
{printf("Keyword: type\n");     return T_type;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "lexical_analyzer.l"
{printf("Keyword: array\n");    return T_array;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "lexical_analyzer.l"
{printf("Keyword: set\n");      return T_set;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 117 "lexical_analyzer.l"
{printf("Keyword: of\n");       return T_of;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 118 "lexical_analyzer.l"
{printf("Keyword: record\n");   return T_record;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 119 "lexical_analyzer.l"
{printf("Keyword: var\n");      return T_var;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 120 "lexical_analyzer.l"
{printf("Keyword: forward\n");  return T_forward;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 121 "lexical_analyzer.l"
{printf("Keyword: function\n"); return T_function;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 122 "lexical_analyzer.l"
{printf("Keyword: procedure\n");return T_procedure;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 123 "lexical_analyzer.l"
{printf("Keyword: integer\n");  return T_integer;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "lexical_analyzer.l"
{printf("Keyword: real\n");     return T_real;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "lexical_analyzer.l"
{printf("Keyword: boolean\n");  return T_boolean;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "lexical_analyzer.l"
{printf("Keyword: char\n");     return T_char;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 127 "lexical_analyzer.l"
{printf("Keyword: begin\n");    return T_begin;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 128 "lexical_analyzer.l"
{printf("Keyword: end\n");      return T_end;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 129 "lexical_analyzer.l"
{printf("Keyword: if\n");       return T_if;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 130 "lexical_analyzer.l"
{printf("Keyword: then\n");     return T_then;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 131 "lexical_analyzer.l"
{printf("Keyword: else\n");     return T_else;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 132 "lexical_analyzer.l"
{printf("Keyword: while\n");    return T_while;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 133 "lexical_analyzer.l"
{printf("Keyword: do\n");       return T_do;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 134 "lexical_analyzer.l"
{printf("Keyword: for\n");      return T_for;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 135 "lexical_analyzer.l"
{printf("Keyword: downto\n");   return T_downto;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "lexical_analyzer.l"
{printf("Keyword: to\n");       return T_to;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "lexical_analyzer.l"
{printf("Keyword: with\n");     return T_with;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 138 "lexical_analyzer.l"
{printf("Keyword: read\n");     return T_read;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 139 "lexical_analyzer.l"
{printf("Keyword: write\n");    return T_write;}
	YY_BREAK

    // RCONST

case 29:
YY_RULE_SETUP
#line 146 "lexical_analyzer.l"
{yylval.real = binary_to_decimal(yytext); printf("Real binary: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "lexical_analyzer.l"
{yylval.real = binary_to_decimal(yytext); printf("Real binary: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "lexical_analyzer.l"
{yylval.real = binary_to_decimal(yytext); printf("Real binary: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 149 "lexical_analyzer.l"
{yylval.real = binary_to_decimal(yytext); printf("Real binary: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 150 "lexical_analyzer.l"
{yylval.real = hex_to_decimal(yytext); printf("Real hex: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "lexical_analyzer.l"
{yylval.real = hex_to_decimal(yytext); printf("Real hex: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 152 "lexical_analyzer.l"
{yylval.real = hex_to_decimal(yytext); printf("Real hex: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "lexical_analyzer.l"
{yylval.real = hex_to_decimal(yytext); printf("Real hex: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "lexical_analyzer.l"
{yylval.real = strtod(yytext, NULL); printf("Real: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "lexical_analyzer.l"
{yylval.real = strtod(yytext, NULL); printf("Real: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 156 "lexical_analyzer.l"
{yylval.real = strtod(yytext, NULL); printf("Real: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 157 "lexical_analyzer.l"
{yylval.real = strtod(yytext, NULL); printf("Real: %lf\n", yylval.real); return T_rconst;}
	YY_BREAK

    // Define rel, add, muldivand and or/not/in operators before the identifiers

case 41:
YY_RULE_SETUP
#line 163 "lexical_analyzer.l"
{printf("Not equal\n");                 return T_relop;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 164 "lexical_analyzer.l"
{printf("Greater than or equal to\n");  return T_relop;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 165 "lexical_analyzer.l"
{printf("Less than or equal to\n");     return T_relop;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 166 "lexical_analyzer.l"
{printf("Greater than\n");              return T_relop;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 167 "lexical_analyzer.l"
{printf("Less than\n");                 return T_relop;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 168 "lexical_analyzer.l"
{printf("Plus\n");                      return T_addop;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 169 "lexical_analyzer.l"
{printf("Minus\n");                     return T_addop;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "lexical_analyzer.l"
{printf("Times\n");                     return T_muldivandop;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 171 "lexical_analyzer.l"
{printf("Divided\n");                   return T_muldivandop;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 172 "lexical_analyzer.l"
{printf("Modulo\n");                    return T_muldivandop;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 173 "lexical_analyzer.l"
{printf("Dividor\n");                   return T_muldivandop;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 174 "lexical_analyzer.l"
{printf("AND\n");                       return T_muldivandop;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 175 "lexical_analyzer.l"
{printf("OR\n");                        return T_or;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 176 "lexical_analyzer.l"
{printf("NOT\n");                       return T_not;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 177 "lexical_analyzer.l"
{printf("IN\n");                        return T_in;}
	YY_BREAK

    // Define constants before the identifiers
    // BCONST

case 56:
YY_RULE_SETUP
#line 184 "lexical_analyzer.l"
{printf("Boolean constant: True\n");  return T_bconst;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 185 "lexical_analyzer.l"
{printf("Boolean constant: False\n"); return T_bconst;}
	YY_BREAK

    // Identifiers

    // [_?]:                optional _ in the beginning
    // [a-zA-z]:            single letter character
    // [_a-zA-Z0-9]*        more
    // ([_]*[a-zA-Z0-9]+)*  underscore(s) with more digits following


case 58:
YY_RULE_SETUP
#line 197 "lexical_analyzer.l"
{printf("Identifier: %s\n", yytext); return T_id;}
	YY_BREAK

    // ICONST

case 59:
YY_RULE_SETUP
#line 204 "lexical_analyzer.l"
{yylval.integer = strtol(yytext + 2, NULL, 16); printf("Integer constant: %d\n", yylval.integer); return T_iconst;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 205 "lexical_analyzer.l"
{yylval.integer = strtol(yytext + 2, NULL, 2); printf("Integer constant: %d\n", yylval.integer); return T_iconst;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "lexical_analyzer.l"
{yylval.integer = atoi(yytext); printf("Integer constant: %d\n", yylval.integer); return T_iconst;}
	YY_BREAK

    // We continue with the other lexical units

case 62:
YY_RULE_SETUP
#line 211 "lexical_analyzer.l"
{printf("Left parenthesis\n");  return T_lparen;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 212 "lexical_analyzer.l"
{printf("Right parenthesis\n"); return T_rparen;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 213 "lexical_analyzer.l"
{printf("Semicolon\n");         return T_semi;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 214 "lexical_analyzer.l"
{printf("Dot\n");               return T_dot;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 215 "lexical_analyzer.l"
{printf("Comma\n");             return T_comma;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 216 "lexical_analyzer.l"
{printf("Equal sign\n");        return T_equ;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 217 "lexical_analyzer.l"
{printf("Colon\n");             return T_colon;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 218 "lexical_analyzer.l"
{printf("Left bracket\n");      return T_lbrack;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 219 "lexical_analyzer.l"
{printf("Right bracket\n");     return T_rbrack;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 220 "lexical_analyzer.l"
{printf("Assign\n");            return T_assign;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 221 "lexical_analyzer.l"
{printf("Dot dot\n");           return T_dotdot;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 222 "lexical_analyzer.l"
{printf("End-of-file\n");       return T_eof;}
	YY_BREAK

    // We will define the rules for the string above the whitespace, because
    // whitespace can be part of a string as well.

case 74:
YY_RULE_SETUP
#line 229 "lexical_analyzer.l"
{ /* String started */ memset(yylval.str , 0, 1024); BEGIN(STRING); }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 230 "lexical_analyzer.l"
{ /* Changing line */ strcat(yylval.str, " "); lines++;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 231 "lexical_analyzer.l"
{ /* Reading normal characters */ strcat(yylval.str, yytext); }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 232 "lexical_analyzer.l"
{ /* Can't expect a newline on it's own */ print_error("Strings must change line with \\ !"); lines++;}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 233 "lexical_analyzer.l"
{ /* Can't expect end of file right now */ print_error("String did not close!");}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 234 "lexical_analyzer.l"
{ /* String ended */ printf("\nString: %s\n", yylval.str); BEGIN(INITIAL); return T_string;}
	YY_BREAK

    // CCONST

case 79:
YY_RULE_SETUP
#line 241 "lexical_analyzer.l"
{printf("Character constant: %s\n", yytext);    return T_cconst;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 242 "lexical_analyzer.l"
{printf("Special character constant\n");        return T_cconst;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 247 "lexical_analyzer.l"
{ /* Comment started */ memset(yylval.str , 0, 1024); BEGIN(COMMENT); }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 248 "lexical_analyzer.l"
{ /* Changing line */   strcat(yylval.str, " "); lines++;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 249 "lexical_analyzer.l"
{ /* Adding the character to the string */strcat(yylval.str, yytext); }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 250 "lexical_analyzer.l"
{ /* Can't expect end of file right now */ print_error("Comment did not close!"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 251 "lexical_analyzer.l"
{ /* Comment ended. Only print it. */ printf("Comment: %s\n", yylval.str); BEGIN(INITIAL);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 253 "lexical_analyzer.l"
{/* Ignore whitespace */}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 254 "lexical_analyzer.l"
{/* Ignore whitespace but increment lines*/ lines++;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 256 "lexical_analyzer.l"
{yylval.integer = 0;            return T_iconst;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 259 "lexical_analyzer.l"
{print_error("Unrecognized character!");}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 261 "lexical_analyzer.l"
ECHO;
	YY_BREAK
#line 1571 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 245);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 261 "lexical_analyzer.l"



double binary_to_decimal(const char* binary_string) {
    // Skip the "0b" prefix
    const char* binary_digits = binary_string + 2;

    // Find the position of the decimal point, if present
    const char* decimal_point = strchr(binary_digits, '.');

    // Calculate the length of the integer part
    int integer_length = decimal_point ? decimal_point - binary_digits : strlen(binary_digits);

    // Convert the integer part to decimal
    double decimal = 0;
    for (int i = 0; i < integer_length; i++) {
        if (binary_digits[i] == '1') {
            decimal += pow(2, integer_length - i - 1);
        }
    }

    // If decimal point exists, calculate the fractional part
    if (decimal_point) {
        int fractional_length = strlen(decimal_point + 1);

        for (int i = 0; i < fractional_length; i++) {
            if (binary_digits[integer_length + 1 + i] == '1') {
                decimal += pow(2, -i - 1);
            }
        }
    }

    return decimal;
}

double hex_to_decimal(const char* hex_string) {
    // Skip the "0h" prefix
    const char* hex_digits = hex_string + 2;

    // Find the position of the decimal point, if present
    const char* decimal_point = strchr(hex_digits, '.');

    // Calculate the length of the integer part
    int integer_length = decimal_point ? decimal_point - hex_digits : strlen(hex_digits);

    // Convert the integer part to decimal
    double decimal = 0;
    for (int i = 0; i < integer_length; i++) {
        char hex_digit = hex_digits[i];

        // Convert hexadecimal digit to decimal
        int decimal_digit;
        if (hex_digit >= '0' && hex_digit <= '9') {
            decimal_digit = hex_digit - '0';
        } else if (hex_digit >= 'A' && hex_digit <= 'F') {
            decimal_digit = hex_digit - 'A' + 10;
        } else if (hex_digit >= 'a' && hex_digit <= 'f') {
            decimal_digit = hex_digit - 'a' + 10;
        } else {
            // Invalid hexadecimal digit
            return 0;
        }

        decimal += decimal_digit * pow(16, integer_length - i - 1);
    }

    // If decimal point exists, calculate the fractional part
    if (decimal_point) {
        int fractional_length = strlen(decimal_point + 1);

        for (int i = 0; i < fractional_length; i++) {
            char hex_digit = hex_digits[integer_length + 1 + i];

            // Convert hexadecimal digit to decimal
            int decimal_digit;
            if (hex_digit >= '0' && hex_digit <= '9') {
                decimal_digit = hex_digit - '0';
            } else if (hex_digit >= 'A' && hex_digit <= 'F') {
                decimal_digit = hex_digit - 'A' + 10;
            } else if (hex_digit >= 'a' && hex_digit <= 'f') {
                decimal_digit = hex_digit - 'a' + 10;
            } else {
                // Invalid hexadecimal digit
                return 0;
            }

            decimal += decimal_digit * pow(16, -i - 1);
        }
    }

    return decimal;
}

void print_error(char *reason)
{
    printf("----ERROR----\n");
    printf("Error in line %d:\n", lines);
    printf("%s\n", reason);
    FILE *fp2 = fopen(filename, "r");
    int i;
    char line[1024];
    for (i=1; i<=lines; i++)
    {
        memset(line, 0, 1024);
        fgets(line, 1024, fp2);
    }
    printf("%s\n", line);
    errors++;
    fclose(fp2);
    // We can only give one chance
    if (errors == 2)
    {
        printf("Too many errors to handle.\n");
        printf("---- END ----\n");
        exit(1);
    }
    else 
    {
        printf("---- END ----\n");
    }
}


int main(int argc, char *argv[])
{
    int token;

    if (argc < 2)
    {
        do {
            token = yylex();
            printf("token value: %d\n", token);
        } while (token!=T_eof);
    }
    else 
    {
        memcpy(filename, argv[1], strlen(argv[1]));
        fp = fopen(argv[1], "r");
        yyin = fopen(argv[1], "r");
        do {
            token = yylex();
            printf("Token value: %d\n", token);
        }   while (token != T_eof);
        fclose(yyin);
    }
    return 0;
}


